version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dead-tunarr_server_1
      APP_PORT: 8069
      PROXY_AUTH_ADD: "false"

  server:
    image: chrisbenincasa/tunarr:0.22.13
    environment:
      - TUNARR_SERVER_PORT=8069
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TUNARR_SERVER_TRUST_PROXY=true
      - TZ=${TZ:-"Europe/Warsaw"}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config/tunarr
    restart: on-failure