version: "3.7"

services:
  server:
    image: chrisbenincasa/tunarr:latest
    ports:
      - 8096:8069
    environment:
      - TUNARR_SERVER_PORT=8069
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TUNARR_SERVER_TRUST_PROXY=true
      - TZ=${TZ:-"Europe/Warsaw"}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config/tunarr
    restart: on-failure